Feat/#23 game api2
ALLBACK-2022/DoodleDoodle-v2 pull request #24
Opened 2023-07-07 17:30 UTC by yunhobb

## 추가/수정한 기능 설명

* game 단어 선택 api 
* draw 저장 api 
<br>

## check list
- [ ] issue number를 브랜치 앞에 추가 하였는가?
- [ ] 모든 단위 테스트를 돌려보고 기존에 작동하던 테스트에 영향이 없는 것을 확인했는가?
- [ ] 추가/수정사항을 설명하였는가?

2023-07-08 12:30 UTC, ohksj77 requested changes
수고했어~

2023-07-08 12:30 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/draw/dto/request/DrawRequset.java
> +public class DrawRequset {
클래스명 (파일명도) Request 로 수정 부탁

2023-07-08 12:30 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/draw/service/DrawService.java
> +@Slf4j
이거 왜 붙인거야?

2023-07-08 12:30 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/draw/service/DrawService.java
> +            String downloadUri = "https://test-bucket-doodle.s3.ap-northeast-2.amazonaws.com/drawimage/"+ draw.getId() + ".png";
이거 좀 보기 안좋아서 getDownloadUri 라고 String 리턴하는 함수 밑에 하나 만들까?

2023-07-08 12:30 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/game/service/GameService.java
> +        EntityNotFoundException::new);
이거 loadEntity 사용해줘!

2023-07-08 12:30 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/game/entity/Game.java
> +    this.id = id;
id를 왜 바꾸지..?

2023-07-08 12:30 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/draw/service/DrawService.java
> +            String downloadUri = "https://test-bucket-doodle.s3.ap-northeast-2.amazonaws.com/drawimage/"+ draw.getId() + ".png";
근데 이거 테스트 해봤어?

2023-07-08 12:30 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/draw/service/DrawService.java
> +            String downloadUri = "https://test-bucket-doodle.s3.ap-northeast-2.amazonaws.com/drawimage/"+ draw.getId() + ".png";
try 보기 안좋긴 한데.. 흠

2023-07-08 23:54 UTC, yunhobb commented on backend/src/main/java/com/doodledoodle/backend/draw/dto/request/DrawRequset.java
> +public class DrawRequset {
실수.. 하하

2023-07-08 23:56 UTC, yunhobb commented on backend/src/main/java/com/doodledoodle/backend/draw/service/DrawService.java
> +@Slf4j
값이 Null로 떠서 로그 찍어보다가 지우는걸 깜빡했네..

2023-07-09 03:22 UTC, yunhobb commented on backend/src/main/java/com/doodledoodle/backend/draw/service/DrawService.java
> +            String downloadUri = "https://test-bucket-doodle.s3.ap-northeast-2.amazonaws.com/drawimage/"+ draw.getId() + ".png";
<img width="616" alt="image" src="https://github.com/ALLBACK-2022/DoodleDoodle-v2/assets/87285536/0d9c7e60-5207-4d32-9edf-f13c3c7706e9">
<br>
이걸로 수정했어~

2023-07-09 03:27 UTC, yunhobb commented on backend/src/main/java/com/doodledoodle/backend/game/entity/Game.java
> +    this.id = id;
이거 내가 잘못생각했어

2023-07-24 12:20 UTC, ohksj77 approved these changes

2023-07-24 18:35 UTC, merged