[feat/#1] entity 생성
ALLBACK-2022/DoodleDoodle-v2 pull request #3
Opened 2023-03-25 09:28 UTC by yunhobb

## 추가/수정한 기능 설명
draw, game, result, dictionary entity 추가
관계는 단방향으로 설정 
<br>

## check list
- [x] issue number를 브랜치 앞에 추가 하였는가?
- [ ] 모든 단위 테스트를 돌려보고 기존에 작동하던 테스트에 영향이 없는 것을 확인했는가?
- [x] 추가/수정사항을 설명하였는가?

2023-03-25 13:15 UTC, ohksj77 requested changes
공통되는 부분은 중복 작성하지 안했어 일단 request changes

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/dictionary/entity/Dictionary.java
> +@Table(name = "DICTIONARY")
테이블명을 모두 대문자로 꼭 하고 싶은거 아니면 @Table은 다 빼도 될듯

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/dictionary/entity/Dictionary.java
> +  @Column(name = "dictionary_id")
우리 저번에는 엔티티 ID 컬럼 명을 다 id로 했었는데 변경하고 싶은건가..? (단순 궁금)

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/dictionary/entity/Dictionary.java
> +  @OneToOne
fetch 타입을 Lazy로 줘야할듯

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/dictionary/entity/Dictionary.java
>  }
음 생성자가 기본 생성자만 있는데 어떻게 생성해..? 다른 생성자 필요할듯

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/draw/entity/Draw.java
> +  @ManyToOne
fetch lazy로 해줘

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/draw/entity/Draw.java
> +  @JoinColumn(name = "game_id")
아 이거 때문에 id 에 다 Column넣은건가? 이거랑 관련 없음

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/draw/entity/Draw.java
> +  @Column(nullable = false)
우리 맨 처음에 doodle 컬럼에 저장 안하고 나중에 업데이트 하는 형식인거 같아 (예전 버전 찾아봤어) 그렇다면 nullable false 주면 아예 저장을 못하게 돼

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/draw/entity/Draw.java
> +  @GeneratedValue(strategy = GenerationType.SEQUENCE)
이거 SEQUENCE로 넣는 경우 @SequenceGenerator도 적용해야하는 거로 알아서 알아봐야 할듯

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/result/entity/Result.java
>  }
여기 3개 다 fetch 설정 해주세용

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/global/config/JpaAuditingConfig.java
> +
비어있는 클래스라면 그냥 어노테이션 메인 클래스에 넣어도 될거 같음

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/game/entity/Game.java
> +import com.doodledoodle.backend.draw.entity.Draw;
전반적으로 import 정리 해주세요.. 안쓰는 애들이 좀 많아

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/game/entity/Game.java
> +
우리 여기에 random word도 컬럼으로 있어야 할듯!

2023-03-25 13:15 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/global/entity/BaseEntity.java
> +public class BaseEntity {
앗.. abstract 일단 적어줘.. 
그리고 이거 embedded로 할지 아니면 추상 클래스로 할지 정하자 다음에

2023-03-25 13:25 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/result/entity/Result.java
>  }
[Fetch설정 Refrence](https://deveric.tistory.com/56)

2023-03-25 14:44 UTC, yunhobb commented on backend/src/main/java/com/doodledoodle/backend/global/entity/BaseEntity.java
> +public class BaseEntity {
이것 실수.. embedded의 장점이 있어?

2023-03-25 14:45 UTC, yunhobb commented on backend/src/main/java/com/doodledoodle/backend/game/entity/Game.java
> +import com.doodledoodle.backend.draw.entity.Draw;
중간에 auto import 설정을 잘못해서.. 수정할께

2023-03-25 14:46 UTC, yunhobb commented on backend/src/main/java/com/doodledoodle/backend/dictionary/entity/Dictionary.java
> +@Table(name = "DICTIONARY")
ㅇㅋㅇㅋ

2023-03-25 14:53 UTC, yunhobb commented on backend/src/main/java/com/doodledoodle/backend/global/config/JpaAuditingConfig.java
> +
이거는 명시적으로 보여주면 좋을거 같아서 이렇게 해놨어

2023-03-25 15:16 UTC, yunhobb commented on backend/src/main/java/com/doodledoodle/backend/dictionary/entity/Dictionary.java
> +  @Column(name = "dictionary_id")
이것도 삭제할께

2023-03-25 16:50 UTC, yunhobb commented on backend/src/main/java/com/doodledoodle/backend/draw/entity/Draw.java
> +  @GeneratedValue(strategy = GenerationType.SEQUENCE)
그럼 indentity로 변경할까?

2023-03-26 04:22 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/draw/entity/Draw.java
> +  @GeneratedValue(strategy = GenerationType.SEQUENCE)
PostgreSQL에 맞게 설정해야하는데 identity도 된다고 하는거 같아.. 일단 identity로 해보고 테스트 필요할듯!

2023-03-26 04:23 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/global/entity/BaseEntity.java
> +public class BaseEntity {
embedded 가 좋은 부분이 있는게 맞는데 embedded의 장점 보다는 abstract클래스의 단점이 좀 있어서..

2023-03-26 04:32 UTC, ohksj77 commented on backend/src/main/java/com/doodledoodle/backend/global/config/JpaAuditingConfig.java
> +
음.. 일단 OK

2023-03-26 04:33 UTC, ohksj77 commented
커밋 할때 다된 부분은 resolve conversation 눌러줘

2023-03-26 04:39 UTC, yunhobb commented on backend/src/main/java/com/doodledoodle/backend/draw/entity/Draw.java
> +  @GeneratedValue(strategy = GenerationType.SEQUENCE)
ㅇㅋㅇㅋ 일단 indentity로 해놨어

2023-03-26 04:40 UTC, yunhobb commented on backend/src/main/java/com/doodledoodle/backend/global/entity/BaseEntity.java
> +public class BaseEntity {
아 그CBU레포에서 봤어 abstract로 하면 상속 하나만 받을 수 있어서 그런거인가?

2023-03-26 04:54 UTC, merged